### ISSUE TITLE
[PDF-export using decktape] phantomjs is not working for windows

### ISSUE THREAD

**Issue by engyasin** [datitran/jupyter-presentation-template#5]
Ok, after trying and browsing for a while , phantomjs in this package is not Windows executable ,
and the one from phantomjs.org not working for decktape.

and the link in :  http://astefanutti.github.io/decktape/downloads/phantomjs-msvc2013-win64.exe
is dead .

npm? failed , the same as [the issue](https://github.com/astefanutti/decktape/issues/114)
any other option I have to get this repo working considering pdf outputting, like providing an exe for windows 

P. S: `?pdf-export` is ugly

**Comment by kuchaale** [comment]
Try to use this link: [https://github.com/astefanutti/decktape/releases/download/v1.0.0/phantomjs-msvc2013-x86.exe](https://github.com/astefanutti/decktape/releases/download/v1.0.0/phantomjs-msvc2013-x86.exe).

**Comment by engyasin** [comment]
Wow , .. it worked
I was trying with it , and now i make a pdf out of slides
I can say it works in arabic language also (`rtl` and `text-align:right` ) and it's beautiful..

there's still bad Mathjack apperance , but i guess it's related to slow connection
