### ISSUE TITLE
run.py always presents the same slideshow

### ISSUE THREAD

**Issue by EstevaoUyra** [datitran/jupyter-presentation-template#7]
It doesn't matter how I change the presentation_template.ipynb, and I can see that presentation_template.slides.html DOES in fact change when I run create_slides.py. 
The slideshow I get when running run.py --file myfilename is always the original template slideshow.

**Comment by datitran** [comment]
This might be a problem of your browser. The cache is not removed and reloaded again. I have this from times to times. Closing it helps or use another browser.
